### ISSUE TITLE
DOI and software paper for v1 release

### ISSUE THREAD

**Issue by cranmer** [histogrammar/histogrammar-multilang#2]
Great progress here, nice to watch.

Once a v1 is ready to be released:
https://guides.github.com/activities/citable-code/

and perhaps
http://joss.theoj.org

**Comment by jpivarski** [comment]
Thanks! That sounds like a good idea. I'll leave this issue open until v1 is actually reached and I have something to submit.

**Comment by jpivarski** [comment]
**Histogrammar-Scala:** [![DOI](https://zenodo.org/badge/doi/10.5281/zenodo.61344.svg)](http://dx.doi.org/10.5281/zenodo.61344)

**Histogrammar-Python:** [![DOI](https://zenodo.org/badge/doi/10.5281/zenodo.61418.svg)](http://dx.doi.org/10.5281/zenodo.61418)

It looks like every little version bump would require a new DOI, which is a huge hassle and potentially confusing to the intended audience. (The release messages describe changes with respect to the previous version, not an introduction to the product as the DOI's "abstract" should. That can be manually edited, along with the authors' incorrectly assigned affiliations, but... every time?) I'll make a new DOI for major revisions or when a publication requires a particular feature and needs to cite the right version.
